Layout ADT-46
nikitavik/uber-coin-frontend pull request #11
Opened 2024-08-14 10:29 UTC by PushkinDenis

2024-08-15 22:25 UTC, PushkinDenis commented on src/app/styles/global.scss
> +$font-large: utils.to-rem(18px);
Положил сюда потому что в  когда лежит variables выдаёт ошибку: 
![image](https://github.com/user-attachments/assets/78640a19-38b1-4700-89d9-87ce1cbd95c4)

2024-08-15 22:25 UTC, PushkinDenis commented on src/app/styles/global.scss
> +    font-size: 14px;
Ага, ставил для мобилки

2024-08-15 22:27 UTC, PushkinDenis commented on src/app/styles/global.scss
>  }
Объясни что не залупа

2024-08-15 22:27 UTC, PushkinDenis commented on src/app/styles/utils.scss
> +$transition-default: $transition-default-duration $transition-default-timing-function !default;
.

2024-08-15 22:37 UTC, PushkinDenis commented on src/entities/account/assets/icons/income/ui/Income.tsx
> +};
.

2024-08-15 22:51 UTC, PushkinDenis commented on src/entities/expense/assets/ui/Burger.tsx
> +};
+

2024-08-16 12:50 UTC, nikitavik requested changes

2024-08-16 12:50 UTC, nikitavik commented on src/widgets/expenses-panel/ui/ExpensesPanel.module.scss
> +}
![image](https://github.com/user-attachments/assets/09399fb3-0784-49a6-ad96-55664719f7db)

Хочу что было не так 
а вот так 

![image](https://github.com/user-attachments/assets/b2c990ce-9fcf-4e47-805b-887177f4dee9)



Грид трат должен работать как и скриншоте
На **1**  должно уходить в оверфолу и прокрутку. делать через `overflow-x: auto;` без переноса аккаунта

2024-08-16 12:50 UTC, nikitavik commented on src/shared/sidebar/ui/Sidebar.tsx
> +            </Popover>
![image](https://github.com/user-attachments/assets/c5ea41df-9734-4f58-9610-3318f4be301f)

Оставь только этот визуальный элемент, логику открытия убери. Компонент **Popover** тут не должен использоваться.

Плюс оставь только этот элемент слева, справа убери

2024-08-16 13:47 UTC, PushkinDenis commented on src/app/styles/global.scss
> +$font-large: utils.to-rem(18px);
+

2024-08-16 13:47 UTC, PushkinDenis commented on src/app/styles/global.scss
>  }
+

2024-08-16 14:00 UTC, PushkinDenis commented on src/shared/sidebar/ui/Sidebar.tsx
> +            </Popover>
+

2024-08-17 11:43 UTC, PushkinDenis commented on src/widgets/expenses-panel/ui/ExpensesPanel.module.scss
> +}
+

2024-08-19 19:16 UTC, nikitavik approved these changes

2024-08-19 21:48 UTC, nikitavik approved these changes

2024-08-19 21:49 UTC, merged