Text field ADT-36
nikitavik/uber-coin-frontend pull request #8
Opened 2024-07-29 04:18 UTC by PushkinDenis

2024-07-30 12:41 UTC, nikitavik commented
Текст инпута дергается на фокус сделай прозрачный `border: Xpx solid transparent;` а на фокусе просто меняй `border-color: sample;`

2024-07-30 13:11 UTC, nikitavik commented
Намудрил с хинтом https://github.com/nikitavik/uber-coin-frontend/pull/8/commits/e483f89417ecaf5fef7471152a2ac097d1b39aa5 смотри

2024-07-30 13:12 UTC, nikitavik commented
И еще `Text-field.tsx` это какойто кэмл кебаб у тебя `**TextField.tsx**`

2024-07-31 06:26 UTC, nikitavik requested changes

2024-07-31 06:26 UTC, nikitavik commented on src/shared/text-field/ui/TextField.module.scss
> +    box-sizing: border-box;
В гобалах пропиши
`* { box-sizing: border-box; }`

2024-07-31 06:26 UTC, nikitavik commented on src/shared/text-field/ui/TextField.module.scss
> +    width: inherit;
Убери

2024-07-31 06:26 UTC, nikitavik commented on src/shared/text-field/ui/TextField.module.scss
> +    height: inherit;
Убери

2024-07-31 06:26 UTC, nikitavik commented on src/shared/text-field/ui/TextField.module.scss
> +        outline: 0;
`outline: none; `в input просто

2024-07-31 06:26 UTC, nikitavik commented on src/shared/text-field/ui/TextField.module.scss
> +    box-sizing: border-box;
Убрать в глобал

2024-07-31 06:26 UTC, nikitavik commented on src/shared/text-field/ui/TextField.module.scss
> +    width: 343px;
Никаких хардкодов ширины элементов вообще, только иконок!

2024-07-31 06:26 UTC, nikitavik commented on src/app/App.tsx
> +                    <TextField label={'lebel'} placeholder={'Placeholder'} ref={ref} />
Еще опечатка, и убери фигурные скобки везде

2024-07-31 06:26 UTC, nikitavik commented on src/shared/text-field/ui/TextField.tsx
> +import WrongIcon from '../../../../assets/icons/wrong.svg?react';
Создай папку assets в text-field.

2024-07-31 06:36 UTC, PushkinDenis commented on vite.config.mts
> +import svgr from 'vite-plugin-svgr';
Делал как тут в Usage. https://www.npmjs.com/package/vite-plugin-svgr

2024-07-31 10:03 UTC, PushkinDenis commented on src/shared/text-field/ui/Text-field.module.scss
> +    box-sizing: border-box;
+

2024-07-31 10:04 UTC, PushkinDenis commented on src/shared/text-field/ui/Text-field.module.scss
> +    height: inherit;
+

2024-07-31 10:05 UTC, PushkinDenis commented on src/shared/text-field/ui/Text-field.module.scss
> +    width: inherit;
+

2024-07-31 10:06 UTC, PushkinDenis commented on src/shared/text-field/ui/Text-field.module.scss
> +        outline: 0;
+

2024-07-31 10:10 UTC, PushkinDenis commented on src/shared/text-field/ui/Text-field.module.scss
> +    box-sizing: border-box;
+

2024-07-31 10:16 UTC, PushkinDenis commented on src/app/App.tsx
> +                <TextField label={'lebel'} placeholder={'Placeholder'} />
+

2024-07-31 10:20 UTC, PushkinDenis commented on src/shared/text-field/ui/Text-field.tsx
> +import WrongIcon from '../../../../assets/icons/wrong.svg?react';
+

2024-07-31 10:21 UTC, PushkinDenis commented on src/shared/text-field/ui/TextField.module.scss
> +    box-sizing: border-box;
+

2024-07-31 10:21 UTC, PushkinDenis commented on src/shared/text-field/ui/TextField.module.scss
> +    height: inherit;
+

2024-07-31 10:21 UTC, PushkinDenis commented on src/shared/text-field/ui/TextField.module.scss
> +        outline: 0;
+

2024-07-31 10:22 UTC, PushkinDenis commented on src/shared/text-field/ui/TextField.module.scss
> +    box-sizing: border-box;
+

2024-07-31 10:22 UTC, PushkinDenis commented on src/shared/text-field/ui/TextField.module.scss
> +    width: 343px;
+

2024-07-31 10:23 UTC, PushkinDenis commented on src/app/App.tsx
> +                    <TextField label={'lebel'} placeholder={'Placeholder'} ref={ref} />
+ ачипатка*

2024-07-31 10:24 UTC, PushkinDenis commented on src/shared/text-field/ui/TextField.tsx
> +import WrongIcon from '../../../../assets/icons/wrong.svg?react';
+

2024-07-31 10:24 UTC, PushkinDenis commented on src/shared/text-field/ui/TextField.module.scss
> +    width: inherit;
+

2024-07-31 10:53 UTC, PushkinDenis commented on src/shared/text-field/ui/Text-field.module.scss
> +    width: 16px;
+

2024-07-31 10:54 UTC, PushkinDenis commented on src/app/App.tsx
> +                    label={'label'}
+

2024-07-31 11:08 UTC, PushkinDenis commented on src/shared/text-field/ui/Text-field.module.scss
> +    width: 343px;
+

2024-08-01 00:58 UTC, PushkinDenis commented on src/shared/text-field/ui/Text-field.module.scss
> +    top: 28%;
+

2024-08-01 07:10 UTC, merged