Log in and sign up modals ADT-39
nikitavik/uber-coin-frontend pull request #9
Opened 2024-08-03 05:19 UTC by PushkinDenis

2024-08-05 15:29 UTC, nikitavik commented on src/shared/text-field/ui/TextField.tsx
> +                            onClick={handleShowPasswordButton}
onClick можно вешать только на интерактивные элементы svg не такой, иконки нужно оборачивать в `<button>`

2024-08-05 15:29 UTC, nikitavik commented on src/shared/text-field/ui/TextField.tsx
> +    isPassword?: boolean;
Вообще сделай так чтоб у тебя было 2 компонента один обычное текстовое поле, другое для пароля.

2024-08-05 15:29 UTC, nikitavik commented on src/shared/text-field/ui/TextField.tsx
> +    isPassword?: boolean;
Вот эта вся логика с иконкой и т.д в отдельном компоненте должна быть, а то ты нагромоздил просто

2024-08-05 15:29 UTC, nikitavik commented on src/shared/text-field/ui/TextField.tsx
> +                    ref={isPassword === true ? refer : ref}
Ну т.е в случае с паролем ты проебал реф сверху

2024-08-05 15:29 UTC, nikitavik commented on src/widgets/log-in-modal/ui/LogInModal.module.scss
> +    width: 300px;
А зачем?

2024-08-05 15:29 UTC, nikitavik commented on src/widgets/sign-up-modal/ui/SignUpModal.tsx
> +                    <TextField label={'Email address'} placeholder={'Email'} />
Опять строку интерполируешь

2024-08-05 15:29 UTC, nikitavik commented on src/widgets/sign-up-modal/ui/SignUpModal.tsx
> +                    <TextField label={'Password'} placeholder={'Password'} isPassword={true} />
И тут тоже

2024-08-05 15:33 UTC, nikitavik commented
А еще давай сделаем одну модалку для авторизации и регистрации. Типо еще не зарегистрировался, жми сюда, и бам контент модалки меняется. Еще сделай чтоб можно было назад вернуться

2024-08-05 15:36 UTC, nikitavik commented
Нужно сделать кнопку которая открывает модалку. Вынеси логику открытия в стору zustand, что мы могли открывать модалку с любой части прилы

2024-08-06 11:03 UTC, PushkinDenis commented on src/widgets/log-in-modal/ui/LogInModal.module.scss
> +    width: 300px;
+ забыл убрать

2024-08-06 11:05 UTC, PushkinDenis commented on src/widgets/sign-up-modal/ui/SignUpModal.tsx
> +                    <TextField label={'Email address'} placeholder={'Email'} />
+ инетрполируй меня полностью

2024-08-06 11:06 UTC, PushkinDenis commented on src/widgets/sign-up-modal/ui/SignUpModal.tsx
> +                    <TextField label={'Password'} placeholder={'Password'} isPassword={true} />
+ полностью интерполируй

2024-08-06 13:51 UTC, PushkinDenis commented on src/shared/text-field/ui/TextField.tsx
> +                            onClick={handleShowPasswordButton}
+

2024-08-06 14:12 UTC, PushkinDenis commented on src/shared/text-field/ui/TextField.tsx
> +                    ref={isPassword === true ? refer : ref}
+ пока убрал, но когда нажимаешь на глаз в пароле, фокус с инпута снимается

2024-08-06 17:08 UTC, nikitavik commented
Осталось только объединить модалки

2024-08-06 17:09 UTC, nikitavik requested changes
Осталось только модалки объединить

2024-08-07 09:54 UTC, nikitavik approved these changes

2024-08-07 09:54 UTC, merged